config/routes.rb
Rails.application.routes.draw do

  resources :signatures, only: [:create],
            defaults: {format: 'json'} do
    collection do
      get :generator
    end
  end

  root 'main#index'

  namespace :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/concerns/signature_generator.rb
require 'RMagick'
require 'aws-sdk'

module SignatureGenerator
  extend ActiveSupport::Concern

  included do
  end

  module ClassMethods
    def generate(data={})
      data.except!('errors', 'validation_context')
      data.except!('changed_attributes', 'previously_changed')

      signature = Signature.new(data)
      signature.generate
    end
  end

  #
  # Generates signature image and saves it
  def generate
    # Trigger all signature image generators
    process
    # Notify with a URL to the waiting client
    notify_client save_signature
  end

  #
  # Define image sizes depending on enterprise
  def signature_size
    sizes = {'tenzing' => { w: 900, h: 200 },
             'default' => { w: 650, h: 200 }}
    @signature_size ||= sizes[enterprise] || sizes['default']
  end

  #
  # Generates image with different sizes and colors depending
  # on enterprise and returns a Magick::Image object
  def image
    sizes = signature_size
    @image ||= Magick::Image.new(sizes[:w], sizes[:h]) {
      self.background_color = 'white'
    }
  end

  #
  # Apply image processing
  def process
    draw_topline
    draw_logos
    draw_texts
  end

  #
  # Draw corporative top line
  def draw_topline
    tline = Magick::Draw.new
    tline.stroke = '#1F3462'
    tline.fill = '#1F3462'
    tline.rectangle 0, 0, signature_size[:w], 4
    tline.draw(image)
  end

  #
  # Draw enterprise logos depending on each case
  def draw_logos
    draw_logo(enterprise, startX = 440)
    draw_logo('urbegi', startX + 250) if enterprise == 'tenzing'
  end


  # Draw the enterprise's logo into the Signature image by using Magick::Draw API
  #
  # ==== Examples
  #
  #   draw_logo('tenzing', 440)
  def draw_logo(enterprise, xPosition)
    # Enterprise logo
    logo = Magick::Image.read(logo_path(enterprise)).first
    image.composite!(logo, xPosition, 40, Magick::OverCompositeOp)
    # Vertical separator
    logo = Magick::Image.read(vseparator_path).first
    image.composite!(logo, xPosition - 40, 20, Magick::OverCompositeOp)
  end

  # Draw signature texts in the correct place inside the signature image
  def draw_texts
    lineTop = 40
    write_text(lineTop += 20, name, '#1F3462', 20, 0) # Name
    write_text(lineTop += 20, role, '#A8A8A8', 16)    # Role

    lineTop += 20
    write_text(lineTop += 20, email,      '#A8A8A8', 16) # Email
    write_text(lineTop += 20, telephone,  '#A8A8A8', 16) # Telephone
    write_text(lineTop += 20, web,        '#A8A8A8', 16) # Webpage
  end

  # Write text into the Signature image by using Magick::Draw API
  # ==== Examples
  #
  #   write_text(20, 'First name & etc', '#1F3462', 20, 0)
  #   write_text(40, 'http://naveda.me', '#A8A8A8', 16)
  def write_text(yPosition, text, color, size, kerning=-0.5)
    @draw ||= Magick::Draw.new
    @draw.font = font_path
    @draw.text_antialias = true
    @draw.stroke = 'transparent'
    @draw.kerning = kerning

    @draw.annotate(image, 0, 0, 40, yPosition, text) {
      self.fill = color
      self.pointsize = size
    }
  end

  # Retrieve the vertical separator path inside the current project
  def vseparator_path
    @vseparator_path ||= "#{Rails.root}/app/assets/images/signatures/separator.png"
  end

  # Retrieve the enterprise's logo path inside the current project
  def logo_path(enterprise)
    "#{Rails.root}/app/assets/images/logos/#{enterprise}.png"
  end

  # Retrieve the text writer font path inside the current project
  def font_path
    @font_path ||= "#{Rails.root}/app/assets/fonts/HelveticaLt.ttf"
  end

  # Saves the image in a temporal path and upload the signature to AWS S3
  def save_signature
    image.write(file_path = "#{Rails.root}/tmp/#{SecureRandom.hex(10)}.png")
    return upload_signature(file_path)
  end

  def upload_signature(file_path)
    s3 = AWS::S3.new
    bucket = s3.buckets[AWS_S3_BUCKET]

    # Upload file to AWS_S3_BUCKET
    key = File.basename("#{name.parameterize}_#{SecureRandom.hex(10)}")
    bucket.objects[key].write(file: file_path, acl: :public_read)

    # Uploaded file remote URL
    "https://s3.amazonaws.com/#{AWS_S3_BUCKET}/#{key}"
  end

  # Notify through redis pubsub
  def notify_client(url)
    Sidekiq.redis { |redis|
      redis.publish(pssid, { url: url }.to_json )
    }
  end

end

app/models/signature.rb
class Signature
  include ActiveModel::Model
  include ActiveModel::Dirty
  include ActiveModel::Validations
  include ActiveModel::Serializers
  extend ActiveModel::Callbacks

  include SignatureGenerator

  define_model_callbacks :save

  attr_accessor :name, :role, :email, :telephone, :web, :enterprise
  attr_accessor :pssid

  validates_presence_of :name, :role, :email

  before_save :default_values
  after_save :async_generate

  def save
    if valid?
      # do persistence work
      changes_applied
      run_callbacks(:save) { true }
    else
      false
    end
  end

  def persisted?
    false
  end

  def default_values
    self.web = self.web.presence || 'http://www.urbegi.com'
    self.telephone = self.telephone.presence || 'Tel. 94 680 19 34'
    self.enterprise = self.enterprise.presence || 'urbegi'
  end

  def async_generate
    SignatureWorker.perform_async(self.as_json)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < InheritedResources::Base
  include Tubesock::Hijack

  respond_to :json, :html

  before_filter :set_pssid

  def generator

    # WebSocket events handler
    hijack do |tubesock|

      # Websocket connection open
      tubesock.onopen do |data|
        tubesock.send_data 'Connected to ws'.to_json
      end

      # Websocket messages receiver
      tubesock.onmessage do |data|

        # Subscribes to redis :pssid channel
        # when client wants to wait for a signature
        if data == 'wait'
          redis.subscribe(session[:pssid]) do |on|
            on.message do |channel, message|
              # Pipe message from SignatureGenerator worker to client
              tubesock.send_data message
              # Close PubSub connection
              ps_unsuscribe
            end
          end
        end

      end

    end

  end

private

  # Request a redis connection from Sidekiq connection pool
  def redis
    @redis ||= Sidekiq.redis { |redis| redis }
  end

  # Set Redis PubSub channel identifier
  def set_pssid
    session[:pssid] ||= SecureRandom.hex(10)
    params.deep_merge!(signature: { pssid: session[:pssid] })
  end

  # Unsuscribe from PubSub channel
  def ps_unsuscribe
    redis.unsubscribe(session[:pssid])
    session[:pssid] = nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Generador de Firmas - Grupo Urbegi
    %meta{:content => 'width=device-width, initial-scale=1', :name => 'viewport'}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = yield

    %footer
      .container
        .row
          .col-xs-12
            %p.text-center &copy; Urbegi Product Research #{Time.now.year}. Todos los derechos reservados.

app/views/main/index.html.haml
%header#signature
  .container
    .row
      .col-xs-12.header-inner
        = link_to 'Grupo Urbegi', root_path, class: 'logo pull-left shake animated'
        .social-icons.text-right.pull-right
          %a{:href => 'https://www.facebook.com/pages/Grupo-Urbegi/684397238292725'}
            %i.fa.fa-facebook

      .clearfix
      .col-xs-12.margin-bottom-20
        .row
          = render partial: 'main/signature/signature'
          = render partial: 'main/signature/options'

%section#generated.section-wrapper.hidden
  .container.fill
    .row.margin-top-30
      .col-xs-12.text-center
        -#.flipInX.animated
        %h2.h1.section-title
          %span
            %i.fa.fa-cloud-download
            Descargar firma
        .clearfix
        #generated-signature
          .image.margin-20
            = image_tag nil, class: 'img-responsive'
          = link_to '#generated', target: :blank, class: 'link' do
            %span.url
            %span.label.label-default
              %i.fa.fa-link

app/views/main/signature/_options.html.haml
.col-xs-12
  #signature-options.margin-bottom-20.animated.flipInX
    .container-fluid
      .row
        .col-xs-12.padding-bottom-10
          .text-align-center.padding-10.padding-top-5
            %h4.heading.padding-5 Selecciona tu empresa dentro del Grupo Urbegi

          .row
            .col-xs-6.col-sm-6.col-md-2.text-align-center.margin-bottom-10
              .btn.btn-default.btn-lg.enterprise-selector.selected{data: { slug: 'urbegi' } }
                = image_tag 'logos/urbegi.png', class: 'img-responsive'
            .col-xs-6.col-sm-6.col-md-2.text-align-center.margin-bottom-10
              .btn.btn-default.btn-lg.enterprise-selector{data: { slug: 'tenzing' } }
                = image_tag 'logos/tenzing.png', class: 'img-responsive'
            .col-xs-6.col-sm-3.col-md-2.text-align-center.margin-bottom-10
              .btn.btn-default.btn-lg.enterprise-selector{data: { slug: 'industriales' } }
                = image_tag 'logos/industriales.png', class: 'img-responsive'
            .col-xs-6.col-sm-3.col-md-2.text-align-center.margin-bottom-10
              .btn.btn-default.btn-lg.enterprise-selector{data: { slug: 'integrales' } }
                = image_tag 'logos/integrales.png', class: 'img-responsive'
            .col-xs-6.col-sm-3.col-md-2.text-align-center.margin-bottom-10
              .btn.btn-default.btn-lg.enterprise-selector{data: { slug: 'medioambiente' } }
                = image_tag 'logos/medioambiente.png', class: 'img-responsive'
            .col-xs-6.col-sm-3.col-md-2.text-align-center.margin-bottom-10
              .btn.btn-default.btn-lg.enterprise-selector{data: { slug: 'upr' } }
                = image_tag 'logos/upr.png', class: 'img-responsive'

app/views/main/signature/_signature.html.haml
.col-xs-12
  .clearfix
  .generator-supertitle.text-align-center.margin-top-15.margin-bottom-20.fadeIn.animated
    %h1.generator-title.margin-0 Genera tu propia firma
    %p Introduce tus datos y podrás generar tu propia firma para identificarte de forma oficial ante tus contactos.
  .signature-generator.margin-20.bounceInDown.animated
    = form_for :signature,url: signatures_url,
                html: { autocomplete: 'off', data: { ws: generator_signatures_path } },
                remote: true do |f|
      .row
        .col-xs-12
          #signature-preview.margin-bottom-10
            .text
              %p.name
                = f.text_field :name, class: 'name',
                                placeholder: 'Nombre Apellido Apellidos',
                                required: true
              %p
                = f.text_field :role,
                                placeholder: 'Cargo',
                                required: true
              %p.email
                = f.email_field :email,
                                placeholder: 'email@urbegi.com',
                                required: true
              %p
                = f.telephone_field :telephone, placeholder: 'Tel. 94 680 19 34'
              %p
                = f.text_field :web, placeholder: 'http://urbegi.com'
            .hidden
              -# Urbegi as default enterprise
              = f.hidden_field :enterprise, value: 'urbegi'
            .separator.hidden-xs.hidden-sm.tenzing.hidden
            .corporate-logo.text-align-center.hidden-xs.hidden-sm.tenzing.hidden
              = image_tag 'logos/tenzing.png'
            .separator.hidden-xs.hidden-sm
            .corporate-logo.main-logo.text-align-center.hidden-xs.hidden-sm
              = image_tag 'logos/urbegi.png'

        .col-xs-12.col-sm-10.actions.text-align-center
          = f.button class: 'btn btn-info btn-lg btn-block',
                     data: { disable_with: 'Generando...' } do
            %i.fa.fa-paperclip
            Generar Firma
        .clearfix.visible-xs.margin-10
        .col-xs-12.col-sm-2.text-align-center
          = link_to '#', id: 'toggleOptions', class: 'btn btn-primary btn-lg btn-block active' do
            %i.fa.fa-cogs
            %span.hidden-sm
              Opciones

app/views/signatures/create.html.haml
%h1 Signatures#create
%p Find me in app/views/signatures/create.html.haml